version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 170821002
      DB_NAME: postgres
    depends_on:
      - db

  db:
    image: postgres:17 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 170821002
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
